version: '3.2'
services:
  database-confluence:
    image: postgres:9.6
    container_name: database-confluence
    environment:
      - POSTGRES_PASSWORD=confluence
      - POSTGRES_USER=confluence
      - POSTGRES_DB=confluence
    networks:
      confluence-cluster-network-701:
        aliases:
          - confluence-cluster-701-db
  confluence:
    image: atlassian/confluence:7.0.1
    container_name: confluence-cluster-701-lb
    links:
      - confluence-net
    ports:
      - 8090:8090
      - 8091:8091
    networks:
      confluence-net:
        aliases:
          - confluence-net

networks:
  confluence-net:
    driver: bridge
