version: '3.2'
services:
  confluence-cluster-701-db:
    image: postgres:9.6
    container_name: confluence-cluster-701-db
    environment:
      - POSTGRES_PASSWORD=confluence
      - POSTGRES_USER=confluence
      - POSTGRES_DB=confluence
    networks:
      confluence-cluster-network-701:
        aliases:
          - confluence-cluster-701-db
  confluence-cluster-701-lb:
    image: codeclou/docker-atlassian-confluence-data-center:loadbalancer-36c4370
    container_name: confluence-cluster-701-lb
    links:
      - confluence-cluster-701-node1
    ports:
      - 2701:2701
    environment:
      - LB_PORT=2701
      - NODES=1
      - NODES_NAME_SCHEMA=confluence-cluster-701-node___NUM___
    networks:
      confluence-cluster-network-701:
        aliases:
          - confluence-cluster-701-lb
  confluence-cluster-701-node1:
    image: atlassian/confluence-server:7.0.1
    container_name: confluence-cluster-701-node1
    links:
      - confluence-cluster-701-db
    environment:
      # Memory / Heap Size
      - JVM_MINIMUM_MEMORY=512M
      - JVM_MAXIMUM_MEMORY=2048M
      # Reverse Proxy Settings
      - ATL_PROXY_NAME=confluence-cluster-701-lb
      - ATL_PROXY_PORT=2701
      # Database
      - ATL_JDBC_URL=jdbc:postgresql://confluence-cluster-701-db:5432/confluence
      - ATL_JDBC_USER=confluence
      - ATL_JDBC_PASSWORD=confluence
      - ATL_DB_TYPE=postgresql
      # Data Center configuration
      - ATL_CLUSTER_TYPE=multicast
      - ATL_CLUSTER_NAME=confluence-cluster
      - ATL_CLUSTER_ADDRESS=230.0.0.1
      - ATL_CLUSTER_TTL=32
      # Home Directories
      - CONFLUENCE_HOME=/opt/confluence-home
      - ATL_PRODUCT_HOME_SHARED=/opt/confluence-home-shared
    volumes:
      - ".confluence-cluster/7.0.1/confluence-home-node1:/opt/confluence-home"
      - ".confluence-cluster/7.0.1/confluence-home-shared:/opt/confluence-home-shared"
    depends_on:
      - confluence-cluster-701-db
    networks:
      confluence-cluster-network-701:
        aliases:
          - confluence-cluster-701-node1



networks:
  confluence-cluster-network-701:
    driver: bridge
